import type { TableMap, TableName } from "./types";

const c = (name: string, hex: string) => ({ name, hex });

export const SEED: { [K in TableName]: TableMap[K][] } = {
  wedding_info: [{
    id: "main",
    date: "2026-11-11T16:00:00+03:00",
    bride: "Shaira",
    groom: "Jeger",
    venue_name: "The Heaven",
    venue_address: "Damistan, Kingdom of Bahrain",
    venue_map_link: "https://maps.google.com/?q=The+Heaven+Damistan+Bahrain",
    venue_map_embed: "https://maps.google.com/maps?q=Damistan%20Bahrain&z=14&output=embed",
    theme_name: "Vintage Lace",
    story: "Two marketers who spent years telling other people's stories finally wrote their own. One brief, one late-night idea, one wish that came true. On 11.11 we make the wish official — and we want you there when we do.",
    instagram: "@shaiandjeg",
    hashtags: ["#JSWeDo", "#JSWishComeTrue"],
    total_budget: 2500,
    currency: "BHD",
    save_the_date_url: "",
    gallery: [],
    cover_photo: "",
    music_url: "",
    rsvp_deadline: "2026-10-25",
  }],
  schedule: [
    { id: "s1", time: "4:00 – 6:00 PM", title: "The Ceremony", detail: "We say I do. Please be seated by 3:45 PM.", order: 1 },
    { id: "s2", time: "6:00 – 7:00 PM", title: "Cocktail Hour", detail: "Filipino street food — isaw, fishballs, kwek-kwek & more.", order: 2 },
    { id: "s3", time: "7:00 – 10:00 PM", title: "The Reception", detail: "Our film on a 120\" screen as lights dim to 20%, a scratch-card game, and a market giveaway.", order: 3 },
  ],
  budget: [
    { id: "b1", category: "Venue", item: "The Heaven, Damistan", quoted_cost: 660, paid_cost: 0, status: "confirmed" },
    { id: "b2", category: "Attire", item: "Bridal dress — Jolaida", quoted_cost: 180, paid_cost: 0, status: "confirmed" },
    { id: "b3", category: "Rings", item: "Wedding rings (est.)", quoted_cost: 350, paid_cost: 0, status: "confirmed" },
    { id: "b4", category: "Attire", item: "Groom suit (est.)", quoted_cost: 100, paid_cost: 0, status: "confirmed" },
    { id: "b5", category: "Sound", item: "Church sound system — FREE", quoted_cost: 0, paid_cost: 0, status: "confirmed" },
    { id: "b6", category: "AV", item: "Projector — ViewSonic (est.)", quoted_cost: 25, paid_cost: 0, status: "confirmed" },
    { id: "b7", category: "Catering", item: "Catering 120 pax (pending decision)", quoted_cost: 394, paid_cost: 0, status: "pending" },
    { id: "b8", category: "Photo / Video", item: "P/V coverage (pending quotes)", quoted_cost: 500, paid_cost: 0, status: "pending" },
  ],
  guests: [],
  vendors: [
    { id: "v1", type: "catering", name: "Shai's Resto", quote: 380, contact: "", status: "quoted", notes: "300 + 80 utensils, 120 pax, lechon included" },
    { id: "v2", type: "catering", name: "Heaven Catering", quote: 394, contact: "", status: "quoted", notes: "2.7/pax × 120 = 324 + outside lechon 70" },
    { id: "v3", type: "p/v", name: "Cinmox", quote: 500, contact: "", status: "quoted", notes: "8 hours coverage" },
    { id: "v4", type: "p/v", name: "Alexandria", quote: 0, contact: "", status: "pending", notes: "Awaiting quote" },
    { id: "v5", type: "p/v", name: "Mark Villaruel", quote: 0, contact: "", status: "pending", notes: "Awaiting quote" },
    { id: "v6", type: "projector", name: "ViewSonic", quote: 25, contact: "", status: "booked", notes: "For 120\" screen video" },
  ],
  checklist: [
    ["Decide caterer: Shai's Resto vs Heaven", "critical", "2026-10-03"],
    ["Collect P/V quotes (Alexandria, Mark Villaruel)", "critical", "2026-10-03"],
    ["Book photo/video team & pay deposit", "critical", "2026-10-08"],
    ["Send Save the Date + website link", "critical", "2026-10-01"],
    ["Confirm church ceremony schedule & sound", "critical", "2026-10-05"],
    ["Order wedding rings", "critical", "2026-10-10"],
    ["First dress fitting with Jolaida", "high", "2026-10-12"],
    ["Groom suit fitting", "high", "2026-10-15"],
    ["Finalize entourage & sponsors list", "high", "2026-10-06"],
    ["Brief bridesmaids on jewel-satin colors", "high", "2026-10-07"],
    ["Book HMUA", "high", "2026-10-10"],
    ["Book band / playlist DJ", "high", "2026-10-14"],
    ["Edit same-day / love-story video for 120\" screen", "high", "2026-11-01"],
    ["RSVP deadline & chase pending guests", "critical", "2026-10-25"],
    ["Final headcount to caterer", "critical", "2026-10-30"],
    ["Print scratch cards for reception game", "medium", "2026-10-28"],
    ["Source market giveaway items", "medium", "2026-10-28"],
    ["Seating plan", "high", "2026-11-02"],
    ["Order cocktail-hour street food", "medium", "2026-10-30"],
    ["Test projector + screen at venue", "medium", "2026-11-05"],
    ["Prepare vows", "high", "2026-11-05"],
    ["Final vendor payments", "critical", "2026-11-08"],
    ["Pack wedding-day emergency kit", "medium", "2026-11-09"],
    ["Rehearsal with entourage", "high", "2026-11-09"],
  ].map(([task, category, due], i) => ({ id: `c${i + 1}`, task, category: category as "critical", due_date: due, completed: false })),
  attire: [
    { id: "a1", group: "bride", label: "The Bride", colors: [c("White", "#F6F1EB")], reserved: true, notes: "", swatch_url: "", order: 1 },
    { id: "a2", group: "groom", label: "The Groom", colors: [c("Black", "#0B0B0B")], reserved: true, notes: "", swatch_url: "", order: 2 },
    { id: "a3", group: "shai_family", label: "Shai's Family", colors: [c("Burgundy", "#6B1D2A")], reserved: true, notes: "", swatch_url: "", order: 3 },
    { id: "a4", group: "jeg_family", label: "Jeg's Family", colors: [c("Teal", "#1F5C5C")], reserved: true, notes: "", swatch_url: "", order: 4 },
    { id: "a5", group: "bridesmaids", label: "Bridesmaids", colors: [c("Amethyst", "#5D3A6B"), c("Magenta", "#8B1E5A"), c("Garnet", "#7A1F2B"), c("Antique Gold", "#B08D4A"), c("Copper", "#A0522D")], reserved: true, notes: "Mixed jewel-tone satin", swatch_url: "", order: 5 },
    { id: "a6", group: "guests", label: "Our Guests", colors: [c("Olive", "#5B5B2E"), c("Moss", "#4A5D23"), c("Forest", "#2F4A2B"), c("Espresso", "#3C2415"), c("Chocolate", "#4E2E1E"), c("Chestnut", "#7B3F26")], reserved: false, notes: "Earth tones please — kindly avoid white, black, burgundy and teal.", swatch_url: "", order: 6 },
  ],
  entourage: [
    { id: "e1", role: "bridesmaid", name: "Maid of Honor", title: "To be announced", order: 1 },
    { id: "e2", role: "groomsman", name: "Best Man", title: "To be announced", order: 2 },
    { id: "e3", role: "sponsor", name: "Principal Sponsors", title: "To be announced", order: 3 },
  ],
  faq: [
    { id: "f1", question: "Can I bring a plus one?", answer: "Your invitation lists your seats. The RSVP lets you choose 1 or 2 pax only if we've reserved two for you.", order: 1 },
    { id: "f2", question: "What should I wear?", answer: "Earth tones — olive, moss, forest, espresso, chocolate, chestnut. Please avoid white, black, burgundy and teal (reserved for us and our families).", order: 2 },
    { id: "f3", question: "Are kids welcome?", answer: "We love your little ones, but this is an adults-only celebration unless they are part of the entourage.", order: 3 },
    { id: "f4", question: "Is there parking?", answer: "Yes, parking is available at The Heaven, Damistan.", order: 4 },
    { id: "f5", question: "Can I post photos?", answer: "Please! Tag @shaiandjeg and use #JSWeDo and #JSWishComeTrue. We only ask for an unplugged ceremony.", order: 5 },
  ],
};
